language: python

python:
  - "3.7"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install pytest-cov
  - pip install pytest-subprocess
  - pip install codecov
  - pip install coloredlogs

install:
  - pip install -r requirements.txt 

script:
  - pytest

after_success:
  - codecov #