language: python	

python:	
  - "3.7"	

before_install:	
  - python --version	
  - pip install -U pip	
  - pip install -U pytest	
  - pip install pytest-cov	
  - pip install pytest-subprocess	
  - pip install codecov	
  - pip install coloredlogs	

install:	
  - sudo apt-get install ffmpeg	
  - pip install -r requirements.txt 	

script:	
  - pytest --cov-report term --cov=app/test/	

env:	
  - CODECOV_TOKEN="f478265b-717e-44dd-9c6a-beb4c0ae95a0"	

after_success:	
  - codecov #	
  - bash <(curl -s https://codecov.io/bash) 