# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'disigen.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpotifyParser(object):
    def setupUi(self, SpotifyParser):
        SpotifyParser.setObjectName("SpotifyParser")
        SpotifyParser.resize(386, 401)
        self.centralwidget = QtWidgets.QWidget(SpotifyParser)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 361, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.alarmTime = QtWidgets.QDateTimeEdit(self.groupBox_2)
        self.alarmTime.setGeometry(QtCore.QRect(20, 80, 321, 22))
        self.alarmTime.setObjectName("alarmTime")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(20, 41, 321, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 150, 361, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.listWidget = QtWidgets.QListWidget(self.groupBox_3)
        self.listWidget.setGeometry(QtCore.QRect(15, 20, 341, 131))
        self.listWidget.setObjectName("listWidget")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 330, 271, 21))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 330, 81, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        SpotifyParser.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SpotifyParser)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 386, 21))
        self.menubar.setObjectName("menubar")
        self.menuSpotifyParser = QtWidgets.QMenu(self.menubar)
        self.menuSpotifyParser.setObjectName("menuSpotifyParser")
        SpotifyParser.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SpotifyParser)
        self.statusbar.setObjectName("statusbar")
        SpotifyParser.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(SpotifyParser)
        self.actionAbout.setObjectName("actionAbout")
        self.menuSpotifyParser.addAction(self.actionAbout)
        self.menubar.addAction(self.menuSpotifyParser.menuAction())

        self.retranslateUi(SpotifyParser)
        QtCore.QMetaObject.connectSlotsByName(SpotifyParser)

    def retranslateUi(self, SpotifyParser):
        _translate = QtCore.QCoreApplication.translate
        SpotifyParser.setWindowTitle(_translate("SpotifyParser", "MainWindow"))
        self.groupBox_2.setTitle(_translate("SpotifyParser", "Поставить будильник"))
        self.alarmTime.setDisplayFormat(_translate("SpotifyParser", "yyyy.MM.dd H:mm"))
        self.lineEdit.setPlaceholderText(_translate("SpotifyParser", "Id spotify плейлиста"))
        self.groupBox_3.setTitle(_translate("SpotifyParser", "Доступные будильники"))
        self.pushButton_2.setText(_translate("SpotifyParser", "Отпрваить"))
        self.menuSpotifyParser.setTitle(_translate("SpotifyParser", "SpotifyParser"))
        self.actionAbout.setText(_translate("SpotifyParser", "About"))
